apiVersion: v1
kind: ConfigMap
metadata:
  name: login-config
data:
  MARIADB_SERVER_ADDR: '10.100.103.115'
  MARIADB_SERVER_PORT: '3306'
  MARIADB_DB_USER: 'root'
  MARIADB_DB_PASSWORD: 'Slime'
  MARIADB_DB_NAME: 'maria-database'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginsvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loginsvc
  template:
    metadata:
      labels:
        app: loginsvc
    spec:
      containers:
        - name: loginsvc
          image: 172.16.0.5:5000/loginsvc
          envFrom:
            - configMapRef:
                name: login-config
---
apiVersion: v1
kind: Service
metadata:
  name: loginsvc-rest
spec:
  selector:
    app: loginsvc
  ports:
    - protocol: TCP
      port: 7070
