apiVersion: v1
kind: ConfigMap
metadata:
  name: posterconf
data:
  LOGIN_SERVER_ADDR: '10.107.225.231'
  LOGIN_SERVER_PORT: '7070'
  MONGO_SERVER_ADDR: '10.109.250.123'
  MONGO_SERVER_PORT: '27017'
  MONGO_DB_USER: delfi
  MONGO_DB_PASSWORD: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postersvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postersvc
  template:
    metadata:
      labels:
        app: postersvc
    spec:
      containers:
        - name: postersvc
          image: 172.16.0.5:5000/postersvc
          envFrom:
            - configMapRef:
                name: posterconf
---
apiVersion: v1
kind: Service
metadata:
  name: postersvc-rest
spec:
  selector:
    app: postersvc
  ports:
    - protocol: TCP
      port: 7075
