apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  MYSQL_ROOT_PASSWORD: 'Slime'
  MYSQL_USER: 'BidenBiden'
  MYSQL_PASSWORD: 'Trump'
  MYSQL_DATABASE: 'maria-database'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: 172.16.0.5:5000/mariasvc
          envFrom:
            - configMapRef:
                name: mariadb-config
          volumeMounts:
            - name: hello
              mountPath: "/var/lib/mysql"
      volumes:
        - name: hello
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariasvc-rest
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
